# Generated by Django 3.0.5 on 2020-05-16 18:53

from django.db import migrations, models
import django.db.models.deletion
import ebay.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_art', models.DateField()),
                ('libelle', models.CharField(max_length=200)),
                ('prix', models.IntegerField()),
                ('devise_sur_le_prix', models.CharField(choices=[('$', '$'), ('€', '€'), ('Fc', 'Fc')], max_length=3)),
                ('commentaire_prix', models.CharField(max_length=255)),
                ('nbr_en_stock', models.IntegerField()),
                ('origin_art', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('valider_art', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_categ', models.DateField()),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImgTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_img', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sous_Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sous', models.DateField()),
                ('libelle_sous', models.CharField(max_length=64)),
                ('description_sous', models.TextField()),
                ('categorie_sous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupe_categorie', to='ebay.Categorie')),
                ('img_sous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImagesSous', to='ebay.ImgTable')),
            ],
        ),
        migrations.CreateModel(
            name='LienImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=64)),
                ('link_img', models.ImageField(blank=True, upload_to=ebay.models.get_upload_images_file_name)),
                ('img_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_table_link', to='ebay.ImgTable')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre_item_choisie', models.IntegerField()),
                ('prix_total', models.FloatField()),
                ('article_commander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Articles_Choisies', to='ebay.Article')),
            ],
        ),
        migrations.AddField(
            model_name='categorie',
            name='img_cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='ebay.ImgTable'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images_Associees', to='ebay.ImgTable'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_sous_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trieCat', to='ebay.Sous_Categorie'),
        ),
    ]
