# Generated by Django 3.0.5 on 2020-05-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sous_categorie',
            old_name='categorie_sous',
            new_name='categorie',
        ),
    ]
