# Generated by Django 3.0.5 on 2020-05-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0002_auto_20200516_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='lienimage',
            name='numero_image',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
