# Generated by Django 3.0.5 on 2020-05-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0003_lienimage_numero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('dateT', models.DateField()),
                ('taille_article', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='description_kin',
            field=models.TextField(default='Test pour description kin Achat Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='taille',
            field=models.ManyToManyField(blank=True, to='ebay.Taille'),
        ),
    ]
