# Generated by Django 3.0.5 on 2020-05-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0005_remove_taille_libelle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='taille',
            new_name='taille_article',
        ),
        migrations.RenameField(
            model_name='taille',
            old_name='taille_article',
            new_name='taille_item',
        ),
    ]
